#!/bin/bash
source ./util.sh

INPUT_DIR=$(mktemp -d -t inputs-XXXXXXX)

__generate_input_files() {
    NUM_FILES=$1
    INTERVAL=$2
    DIR=$3

    for i in $(seq 1 $NUM_FILES); do
        echo "hello world $i" > $DIR/f_$i.txt
        sleep $INTERVAL
    done
}
export -f __generate_input_files

sudo yum install tree

__setup
__start_ensemble_mgr
################################################################################
##### BEGIN EXAMPLE ENSEMBLE MANAGER USAGE #####################################
################################################################################

echo "Creating ensemble called 'myruns'"
pegasus-em create myruns

echo "Creating file pattern cron trigger"
pegasus-em file-pattern-trigger myruns \
    10s_txt \
    10s \
    ./workflows/wf-trigger/workflow.py \
    "$INPUT_DIR/*.txt" \
    --timeout 120s

# generate a new input file f_j.txt for 1 <= j <= NUM_FILES every INTERVAL seconds
# in an input directory
NUM_FILES=100
INTERVAL=2
nohup bash -c "__generate_input_files $NUM_FILES $INTERVAL $INPUT_DIR" >/dev/null 2>&1 &
FILE_GEN_PID=$!

# watch file tree
timeout --foreground 30 watch -n 1 tree $INPUT_DIR

# look at workflow progress
timeout --foreground 30 watch -n 1 pegasus-em workflows myruns

# check output generated by workflow 
ls -alh ~/workflows/workflow-trigger
cat ~/workflows/workflow-trigger/*.txt

################################################################################
##### END EXAMPLE ENSEMBLE MANAGER USAGE #######################################
################################################################################
kill $FILE_GEN_PID
rm -r $INPUT_DIR